# Generated by Django 5.1.1 on 2024-09-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M3U8Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=512)),
                ('up_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
